import React from 'react'
import Head from 'next/head'
import Navbar from '../comps/Navbar'
import Hero from '../comps/hero'
import About from '../comps/About'
import Product from '../comps/Product'
import Subscribe from '../comps/Subscribe'
import Footer from '../comps/Footer'
import Token from './Token'


const Homes  = () => {
     
    return ( <>
    <Head>
        <title>Pak Thaika
        </title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#f69435"/> */}
        {/* <link rel="apple-touch-icon" href="/icon-192x192.png"></link> */}
        <link rel="icon" href="/icon.png" />
        <link href="https://fonts.googleapis.com/css2?family=Rubik&display=swap" rel="stylesheet"/>
      </Head>
     <Navbar />
         <Hero />
         <About/>
         <Product/>
         <Subscribe/> 
        <Footer />
       
     
    </> );
}
 
export default Homes ;