import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Grid } from '@mui/material'
import Homes from './Home'
export default function Home() {
  return (
    <Grid className={styles.container}>
      <Head>
        <title>Pak Thaika
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
        <link href="https://fonts.googleapis.com/css2?family=Rubik&display=swap" rel="stylesheet"/>
      </Head>
       <Homes />
        
    </Grid>
  )
}
